# Generated by Django 5.0.3 on 2024-03-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
