# Generated by Django 4.2.11 on 2024-04-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_id_alter_customuser_age_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='userid',
            new_name='user_id',
        ),
    ]
