# Generated by Django 5.0.1 on 2024-04-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_book_quantity_order_account_number_order_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(blank=True, default=80),
        ),
    ]
