# Generated by Django 4.2.11 on 2024-04-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_review_comment_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='book',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
